//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prisma.AD.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Categoria = new HashSet<Categoria>();
            this.Antiguedad = new HashSet<Antiguedad>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int NumeroDocumento { get; set; }
        public string Legajo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Calle { get; set; }
        public short Altura { get; set; }
        public string PisoDto { get; set; }
        public int TipoDocumentoId { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Antiguedad> Antiguedad { get; set; }
    }
}
