//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prisma.AD.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrismaContainer : DbContext
    {
        public PrismaContainer()
            : base("name=PrismaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empleado> EmpleadoSet { get; set; }
        public DbSet<TipoDocumento> TipoDocumentoSet { get; set; }
        public DbSet<Categoria> CategoriaSet { get; set; }
        public DbSet<Localidad> LocalidadSet { get; set; }
        public DbSet<Provincia> ProvinciaSet { get; set; }
        public DbSet<Pais> PaisSet { get; set; }
        public DbSet<Antiguedad> AntiguedadSet { get; set; }
        public DbSet<AntiguedadDetalle> AntiguedadDetalleSet { get; set; }
        public DbSet<Establecimiento> EstablecimientoSet { get; set; }
    }
}
