//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Prisma", "EmpleadoTipoDocumento", "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Empleado), "TipoDocumento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Prisma.AD.Modelo.TipoDocumento))]
[assembly: EdmRelationshipAttribute("Prisma", "EmpleadoCategoria", "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Empleado), "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Categoria))]
[assembly: EdmRelationshipAttribute("Prisma", "ProvinciaPais", "Provincia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Provincia), "Pais", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Prisma.AD.Modelo.Pais))]
[assembly: EdmRelationshipAttribute("Prisma", "LocalidadProvincia", "Localidad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Localidad), "Provincia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Prisma.AD.Modelo.Provincia))]
[assembly: EdmRelationshipAttribute("Prisma", "EmpleadoLocalidad", "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Empleado), "Localidad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Prisma.AD.Modelo.Localidad))]
[assembly: EdmRelationshipAttribute("Prisma", "AntiguedadEmpleado", "Antiguedad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Antiguedad), "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.Empleado))]
[assembly: EdmRelationshipAttribute("Prisma", "AntiguedadDetalleAntiguedad", "AntiguedadDetalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.AntiguedadDetalle), "Antiguedad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Prisma.AD.Modelo.Antiguedad))]
[assembly: EdmRelationshipAttribute("Prisma", "EstablecimientoAntiguedadDetalle", "Establecimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Prisma.AD.Modelo.Establecimiento), "AntiguedadDetalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Prisma.AD.Modelo.AntiguedadDetalle))]

#endregion

namespace Prisma.AD.Modelo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PrismaContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PrismaContainer object using the connection string found in the 'PrismaContainer' section of the application configuration file.
        /// </summary>
        public PrismaContainer() : base("name=PrismaContainer", "PrismaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrismaContainer object.
        /// </summary>
        public PrismaContainer(string connectionString) : base(connectionString, "PrismaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrismaContainer object.
        /// </summary>
        public PrismaContainer(EntityConnection connection) : base(connection, "PrismaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Empleado> Empleados
        {
            get
            {
                if ((_Empleados == null))
                {
                    _Empleados = base.CreateObjectSet<Empleado>("Empleados");
                }
                return _Empleados;
            }
        }
        private ObjectSet<Empleado> _Empleados;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoDocumento> TiposDocumento
        {
            get
            {
                if ((_TiposDocumento == null))
                {
                    _TiposDocumento = base.CreateObjectSet<TipoDocumento>("TiposDocumento");
                }
                return _TiposDocumento;
            }
        }
        private ObjectSet<TipoDocumento> _TiposDocumento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categoria> Categorias
        {
            get
            {
                if ((_Categorias == null))
                {
                    _Categorias = base.CreateObjectSet<Categoria>("Categorias");
                }
                return _Categorias;
            }
        }
        private ObjectSet<Categoria> _Categorias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Localidad> Localidades
        {
            get
            {
                if ((_Localidades == null))
                {
                    _Localidades = base.CreateObjectSet<Localidad>("Localidades");
                }
                return _Localidades;
            }
        }
        private ObjectSet<Localidad> _Localidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Provincia> Provincias
        {
            get
            {
                if ((_Provincias == null))
                {
                    _Provincias = base.CreateObjectSet<Provincia>("Provincias");
                }
                return _Provincias;
            }
        }
        private ObjectSet<Provincia> _Provincias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pais> Paises
        {
            get
            {
                if ((_Paises == null))
                {
                    _Paises = base.CreateObjectSet<Pais>("Paises");
                }
                return _Paises;
            }
        }
        private ObjectSet<Pais> _Paises;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Antiguedad> Antiguedades
        {
            get
            {
                if ((_Antiguedades == null))
                {
                    _Antiguedades = base.CreateObjectSet<Antiguedad>("Antiguedades");
                }
                return _Antiguedades;
            }
        }
        private ObjectSet<Antiguedad> _Antiguedades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AntiguedadDetalle> AntiguedadesDetalle
        {
            get
            {
                if ((_AntiguedadesDetalle == null))
                {
                    _AntiguedadesDetalle = base.CreateObjectSet<AntiguedadDetalle>("AntiguedadesDetalle");
                }
                return _AntiguedadesDetalle;
            }
        }
        private ObjectSet<AntiguedadDetalle> _AntiguedadesDetalle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Establecimiento> Establecimientos
        {
            get
            {
                if ((_Establecimientos == null))
                {
                    _Establecimientos = base.CreateObjectSet<Establecimiento>("Establecimientos");
                }
                return _Establecimientos;
            }
        }
        private ObjectSet<Establecimiento> _Establecimientos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Empleados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmpleados(Empleado empleado)
        {
            base.AddObject("Empleados", empleado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TiposDocumento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTiposDocumento(TipoDocumento tipoDocumento)
        {
            base.AddObject("TiposDocumento", tipoDocumento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categorias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategorias(Categoria categoria)
        {
            base.AddObject("Categorias", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Localidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocalidades(Localidad localidad)
        {
            base.AddObject("Localidades", localidad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Provincias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProvincias(Provincia provincia)
        {
            base.AddObject("Provincias", provincia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Paises EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaises(Pais pais)
        {
            base.AddObject("Paises", pais);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Antiguedades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAntiguedades(Antiguedad antiguedad)
        {
            base.AddObject("Antiguedades", antiguedad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AntiguedadesDetalle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAntiguedadesDetalle(AntiguedadDetalle antiguedadDetalle)
        {
            base.AddObject("AntiguedadesDetalle", antiguedadDetalle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Establecimientos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstablecimientos(Establecimiento establecimiento)
        {
            base.AddObject("Establecimientos", establecimiento);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Antiguedad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Antiguedad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Antiguedad object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Antiguedad CreateAntiguedad(global::System.Int32 id, global::System.DateTime fecha)
        {
            Antiguedad antiguedad = new Antiguedad();
            antiguedad.Id = id;
            antiguedad.Fecha = fecha;
            return antiguedad;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "AntiguedadEmpleado", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("Prisma.AntiguedadEmpleado", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("Prisma.AntiguedadEmpleado", "Empleado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "AntiguedadDetalleAntiguedad", "AntiguedadDetalle")]
        public EntityCollection<AntiguedadDetalle> AntiguedadDetalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AntiguedadDetalle>("Prisma.AntiguedadDetalleAntiguedad", "AntiguedadDetalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AntiguedadDetalle>("Prisma.AntiguedadDetalleAntiguedad", "AntiguedadDetalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="AntiguedadDetalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AntiguedadDetalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AntiguedadDetalle object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fecha_desde">Initial value of the fecha_desde property.</param>
        /// <param name="fecha_hasta">Initial value of the fecha_hasta property.</param>
        /// <param name="dif_anios">Initial value of the dif_anios property.</param>
        /// <param name="dif_meses">Initial value of the dif_meses property.</param>
        /// <param name="dif_dias">Initial value of the dif_dias property.</param>
        public static AntiguedadDetalle CreateAntiguedadDetalle(global::System.Int32 id, global::System.DateTime fecha_desde, global::System.DateTime fecha_hasta, global::System.Int16 dif_anios, global::System.Int16 dif_meses, global::System.Int16 dif_dias)
        {
            AntiguedadDetalle antiguedadDetalle = new AntiguedadDetalle();
            antiguedadDetalle.Id = id;
            antiguedadDetalle.fecha_desde = fecha_desde;
            antiguedadDetalle.fecha_hasta = fecha_hasta;
            antiguedadDetalle.dif_anios = dif_anios;
            antiguedadDetalle.dif_meses = dif_meses;
            antiguedadDetalle.dif_dias = dif_dias;
            return antiguedadDetalle;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_desde
        {
            get
            {
                return _fecha_desde;
            }
            set
            {
                Onfecha_desdeChanging(value);
                ReportPropertyChanging("fecha_desde");
                _fecha_desde = StructuralObject.SetValidValue(value, "fecha_desde");
                ReportPropertyChanged("fecha_desde");
                Onfecha_desdeChanged();
            }
        }
        private global::System.DateTime _fecha_desde;
        partial void Onfecha_desdeChanging(global::System.DateTime value);
        partial void Onfecha_desdeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_hasta
        {
            get
            {
                return _fecha_hasta;
            }
            set
            {
                Onfecha_hastaChanging(value);
                ReportPropertyChanging("fecha_hasta");
                _fecha_hasta = StructuralObject.SetValidValue(value, "fecha_hasta");
                ReportPropertyChanged("fecha_hasta");
                Onfecha_hastaChanged();
            }
        }
        private global::System.DateTime _fecha_hasta;
        partial void Onfecha_hastaChanging(global::System.DateTime value);
        partial void Onfecha_hastaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 dif_anios
        {
            get
            {
                return _dif_anios;
            }
            set
            {
                Ondif_aniosChanging(value);
                ReportPropertyChanging("dif_anios");
                _dif_anios = StructuralObject.SetValidValue(value, "dif_anios");
                ReportPropertyChanged("dif_anios");
                Ondif_aniosChanged();
            }
        }
        private global::System.Int16 _dif_anios;
        partial void Ondif_aniosChanging(global::System.Int16 value);
        partial void Ondif_aniosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 dif_meses
        {
            get
            {
                return _dif_meses;
            }
            set
            {
                Ondif_mesesChanging(value);
                ReportPropertyChanging("dif_meses");
                _dif_meses = StructuralObject.SetValidValue(value, "dif_meses");
                ReportPropertyChanged("dif_meses");
                Ondif_mesesChanged();
            }
        }
        private global::System.Int16 _dif_meses;
        partial void Ondif_mesesChanging(global::System.Int16 value);
        partial void Ondif_mesesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 dif_dias
        {
            get
            {
                return _dif_dias;
            }
            set
            {
                Ondif_diasChanging(value);
                ReportPropertyChanging("dif_dias");
                _dif_dias = StructuralObject.SetValidValue(value, "dif_dias");
                ReportPropertyChanged("dif_dias");
                Ondif_diasChanged();
            }
        }
        private global::System.Int16 _dif_dias;
        partial void Ondif_diasChanging(global::System.Int16 value);
        partial void Ondif_diasChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "AntiguedadDetalleAntiguedad", "Antiguedad")]
        public Antiguedad Antiguedad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Antiguedad>("Prisma.AntiguedadDetalleAntiguedad", "Antiguedad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Antiguedad>("Prisma.AntiguedadDetalleAntiguedad", "Antiguedad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Antiguedad> AntiguedadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Antiguedad>("Prisma.AntiguedadDetalleAntiguedad", "Antiguedad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Antiguedad>("Prisma.AntiguedadDetalleAntiguedad", "Antiguedad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EstablecimientoAntiguedadDetalle", "Establecimiento")]
        public Establecimiento Establecimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establecimiento>("Prisma.EstablecimientoAntiguedadDetalle", "Establecimiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establecimiento>("Prisma.EstablecimientoAntiguedadDetalle", "Establecimiento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establecimiento> EstablecimientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establecimiento>("Prisma.EstablecimientoAntiguedadDetalle", "Establecimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establecimiento>("Prisma.EstablecimientoAntiguedadDetalle", "Establecimiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Categoria CreateCategoria(global::System.Int32 id, global::System.String descripcion)
        {
            Categoria categoria = new Categoria();
            categoria.Id = id;
            categoria.Descripcion = descripcion;
            return categoria;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EmpleadoCategoria", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("Prisma.EmpleadoCategoria", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("Prisma.EmpleadoCategoria", "Empleado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Empleado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Empleado object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="numeroDocumento">Initial value of the NumeroDocumento property.</param>
        /// <param name="legajo">Initial value of the Legajo property.</param>
        /// <param name="telefono">Initial value of the Telefono property.</param>
        /// <param name="celular">Initial value of the Celular property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="calle">Initial value of the Calle property.</param>
        /// <param name="altura">Initial value of the Altura property.</param>
        /// <param name="pisoDto">Initial value of the PisoDto property.</param>
        /// <param name="tipoDocumentoId">Initial value of the TipoDocumentoId property.</param>
        public static Empleado CreateEmpleado(global::System.Int32 id, global::System.String nombre, global::System.String apellido, global::System.Int32 numeroDocumento, global::System.String legajo, global::System.String telefono, global::System.String celular, global::System.String email, global::System.String calle, global::System.Int16 altura, global::System.String pisoDto, global::System.Int32 tipoDocumentoId)
        {
            Empleado empleado = new Empleado();
            empleado.Id = id;
            empleado.Nombre = nombre;
            empleado.Apellido = apellido;
            empleado.NumeroDocumento = numeroDocumento;
            empleado.Legajo = legajo;
            empleado.Telefono = telefono;
            empleado.Celular = celular;
            empleado.Email = email;
            empleado.Calle = calle;
            empleado.Altura = altura;
            empleado.PisoDto = pisoDto;
            empleado.TipoDocumentoId = tipoDocumentoId;
            return empleado;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false, "Apellido");
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumeroDocumento
        {
            get
            {
                return _NumeroDocumento;
            }
            set
            {
                OnNumeroDocumentoChanging(value);
                ReportPropertyChanging("NumeroDocumento");
                _NumeroDocumento = StructuralObject.SetValidValue(value, "NumeroDocumento");
                ReportPropertyChanged("NumeroDocumento");
                OnNumeroDocumentoChanged();
            }
        }
        private global::System.Int32 _NumeroDocumento;
        partial void OnNumeroDocumentoChanging(global::System.Int32 value);
        partial void OnNumeroDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Legajo
        {
            get
            {
                return _Legajo;
            }
            set
            {
                OnLegajoChanging(value);
                ReportPropertyChanging("Legajo");
                _Legajo = StructuralObject.SetValidValue(value, false, "Legajo");
                ReportPropertyChanged("Legajo");
                OnLegajoChanged();
            }
        }
        private global::System.String _Legajo;
        partial void OnLegajoChanging(global::System.String value);
        partial void OnLegajoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false, "Telefono");
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, false, "Celular");
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Calle
        {
            get
            {
                return _Calle;
            }
            set
            {
                OnCalleChanging(value);
                ReportPropertyChanging("Calle");
                _Calle = StructuralObject.SetValidValue(value, false, "Calle");
                ReportPropertyChanged("Calle");
                OnCalleChanged();
            }
        }
        private global::System.String _Calle;
        partial void OnCalleChanging(global::System.String value);
        partial void OnCalleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Altura
        {
            get
            {
                return _Altura;
            }
            set
            {
                OnAlturaChanging(value);
                ReportPropertyChanging("Altura");
                _Altura = StructuralObject.SetValidValue(value, "Altura");
                ReportPropertyChanged("Altura");
                OnAlturaChanged();
            }
        }
        private global::System.Int16 _Altura;
        partial void OnAlturaChanging(global::System.Int16 value);
        partial void OnAlturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PisoDto
        {
            get
            {
                return _PisoDto;
            }
            set
            {
                OnPisoDtoChanging(value);
                ReportPropertyChanging("PisoDto");
                _PisoDto = StructuralObject.SetValidValue(value, false, "PisoDto");
                ReportPropertyChanged("PisoDto");
                OnPisoDtoChanged();
            }
        }
        private global::System.String _PisoDto;
        partial void OnPisoDtoChanging(global::System.String value);
        partial void OnPisoDtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoDocumentoId
        {
            get
            {
                return _TipoDocumentoId;
            }
            set
            {
                OnTipoDocumentoIdChanging(value);
                ReportPropertyChanging("TipoDocumentoId");
                _TipoDocumentoId = StructuralObject.SetValidValue(value, "TipoDocumentoId");
                ReportPropertyChanged("TipoDocumentoId");
                OnTipoDocumentoIdChanged();
            }
        }
        private global::System.Int32 _TipoDocumentoId;
        partial void OnTipoDocumentoIdChanging(global::System.Int32 value);
        partial void OnTipoDocumentoIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EmpleadoTipoDocumento", "TipoDocumento")]
        public TipoDocumento TipoDocumento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoDocumento>("Prisma.EmpleadoTipoDocumento", "TipoDocumento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoDocumento>("Prisma.EmpleadoTipoDocumento", "TipoDocumento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoDocumento> TipoDocumentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoDocumento>("Prisma.EmpleadoTipoDocumento", "TipoDocumento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoDocumento>("Prisma.EmpleadoTipoDocumento", "TipoDocumento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EmpleadoCategoria", "Categoria")]
        public EntityCollection<Categoria> Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Categoria>("Prisma.EmpleadoCategoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Categoria>("Prisma.EmpleadoCategoria", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EmpleadoLocalidad", "Localidad")]
        public Localidad Localidad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localidad>("Prisma.EmpleadoLocalidad", "Localidad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localidad>("Prisma.EmpleadoLocalidad", "Localidad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Localidad> LocalidadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localidad>("Prisma.EmpleadoLocalidad", "Localidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Localidad>("Prisma.EmpleadoLocalidad", "Localidad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "AntiguedadEmpleado", "Antiguedad")]
        public EntityCollection<Antiguedad> Antiguedad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Antiguedad>("Prisma.AntiguedadEmpleado", "Antiguedad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Antiguedad>("Prisma.AntiguedadEmpleado", "Antiguedad", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Establecimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Establecimiento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Establecimiento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Establecimiento CreateEstablecimiento(global::System.Int32 id, global::System.String descripcion)
        {
            Establecimiento establecimiento = new Establecimiento();
            establecimiento.Id = id;
            establecimiento.Descripcion = descripcion;
            return establecimiento;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EstablecimientoAntiguedadDetalle", "AntiguedadDetalle")]
        public EntityCollection<AntiguedadDetalle> AntiguedadDetalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AntiguedadDetalle>("Prisma.EstablecimientoAntiguedadDetalle", "AntiguedadDetalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AntiguedadDetalle>("Prisma.EstablecimientoAntiguedadDetalle", "AntiguedadDetalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Localidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Localidad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Localidad object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Localidad CreateLocalidad(global::System.Int32 id, global::System.String descripcion)
        {
            Localidad localidad = new Localidad();
            localidad.Id = id;
            localidad.Descripcion = descripcion;
            return localidad;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "LocalidadProvincia", "Provincia")]
        public Provincia Provincia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincia>("Prisma.LocalidadProvincia", "Provincia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincia>("Prisma.LocalidadProvincia", "Provincia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provincia> ProvinciaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincia>("Prisma.LocalidadProvincia", "Provincia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provincia>("Prisma.LocalidadProvincia", "Provincia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EmpleadoLocalidad", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("Prisma.EmpleadoLocalidad", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("Prisma.EmpleadoLocalidad", "Empleado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Pais")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pais : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pais object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Pais CreatePais(global::System.Int32 id, global::System.String descripcion)
        {
            Pais pais = new Pais();
            pais.Id = id;
            pais.Descripcion = descripcion;
            return pais;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "ProvinciaPais", "Provincia")]
        public EntityCollection<Provincia> Provincia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Provincia>("Prisma.ProvinciaPais", "Provincia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Provincia>("Prisma.ProvinciaPais", "Provincia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="Provincia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Provincia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Provincia object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Provincia CreateProvincia(global::System.Int32 id, global::System.String descripcion)
        {
            Provincia provincia = new Provincia();
            provincia.Id = id;
            provincia.Descripcion = descripcion;
            return provincia;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "ProvinciaPais", "Pais")]
        public Pais Pais
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pais>("Prisma.ProvinciaPais", "Pais").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pais>("Prisma.ProvinciaPais", "Pais").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pais> PaisReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pais>("Prisma.ProvinciaPais", "Pais");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pais>("Prisma.ProvinciaPais", "Pais", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "LocalidadProvincia", "Localidad")]
        public EntityCollection<Localidad> Localidad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Localidad>("Prisma.LocalidadProvincia", "Localidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Localidad>("Prisma.LocalidadProvincia", "Localidad", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Prisma", Name="TipoDocumento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoDocumento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoDocumento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static TipoDocumento CreateTipoDocumento(global::System.Int32 id, global::System.String descripcion)
        {
            TipoDocumento tipoDocumento = new TipoDocumento();
            tipoDocumento.Id = id;
            tipoDocumento.Descripcion = descripcion;
            return tipoDocumento;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Prisma", "EmpleadoTipoDocumento", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("Prisma.EmpleadoTipoDocumento", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("Prisma.EmpleadoTipoDocumento", "Empleado", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
